In [2]:
for i in "banana":
    print (i)

b
a
n
a
n
a


In [4]:
a="banana"
for i in a:
    print(i)

b
a
n
a
n
a


In [ ]:
x=["ali","ahmad","qasim","Naseem"]

for i in range(len(x)):
    j=x[i]
    print(j)

ali
ahmad
qasim
Naseem


In [18]:
x=["ali","ahmad","qasim","Naseem"]

for i in x[1:3]:
    print(i)

ahmad
qasim


In [20]:
#function to calculate two numbers

def sum(a,b):
    c=a+b
    return c

print (sum(3,2))

5


In [ ]:
def sum(a,b):
    c=a+b
    return c

def main():
    print(sum(5,3))

if __name__=="__main__":
    main();

8


In [ ]:
a= int(input("Enter a Number: "))
num=0

for i in range(1,a+1):
    num=num+i

print(num)

15


In [5]:
a=int(input("Enter the number: "))
num=0;
i=0;
while i<a+1:
   num=num+i;
   i=i+1

print(num)

15


In [16]:
word=input("Enter the word")
word=word.lower()
palindrome=True
bword=word[::-1]
print(bword)

for i in range(len(bword)):
    if bword[i]!=word[i]:
        palindrome=False
        break

if palindrome:
    print("Palindrome: True")
else:
    print("Palindrome:False")
    

momom
Palindrome: True


In [1]:
string=input("Enter a string: ")
vowels = {'a', 'A', 'e', 'E', 'i', 'I', 'o', 'O', 'u', 'U'}
for i in string:
    if i not in vowels:
        string+=i


print(nstring)

pkstn


In [14]:
# First I am checking the constraints and getting Accurate input:

word1=input("Enter the word1: 1<=Word_len<=100 and all letters should be lowercase")

while len(word1)>100 or len(word1)<1 or not word1.islower() or not word1.isalpha():
    word1 = input("Remember the constraint: ");

print(word1)

word2=input("Enter the word2: 1<=Word_len<=100 and all letters should be lowercase")

while len(word2)>100 or len(word2)<1 or not word2.islower() or not word2.isalpha():
    word2 = input("Remember the constraint: ");

print(word2)

# Now I am merging these:

combined_word=""

for i in range(min(len(word1),len(word2))):
    combined_word+=word1[i] + word2[i]

if len(word1)>len(word2):
    combined_word+=word1[len(word2):]

if len(word2)>len(word1):
    combined_word+=word2[len(word1):]

print(combined_word)

ali
ahmad
aalhimad


In [36]:
class Solution(object):
    def gcdOfStrings(self, str1, str2):
        # Input validation
        if len(str1) < 1 or len(str1) > 100 or not str1.isalpha() or not str1.isupper():
            return ""
        if len(str2) < 1 or len(str2) > 100 or not str2.isalpha() or not str2.isupper():
            return ""

        # Check if strings can have a common divisor
        if str1 + str2 != str2 + str1:
            return ""

        # Start with the shorter string as the initial GCD candidate
        gcd = str2 if len(str2) <= len(str1) else str1

        # Try all possible prefixes of the candidate
        for length in range(len(gcd), 0, -1):
            candidate = gcd[:length]
            # Check if candidate can form both str1 and str2
            if (len(str1) % len(candidate) == 0 and 
                len(str2) % len(candidate) == 0 and
                candidate * (len(str1) // len(candidate)) == str1 and
                candidate * (len(str2) // len(candidate)) == str2):
                return candidate

        return ""

# Test
s = Solution()
print(s.gcdOfStrings("ABABAB", "ABAB"))  # Output: "AB"

AB


In [32]:
string1=["ali","ahmad","kamran"]

for i in range(len(string1)):
    if string1[i]=="ahmad":
       print("hello")


hello


In [57]:
class Solution(object):
    def gcdOfStrings(self, str1, str2):

        
        if str1 + str2 != str2 + str1:
            return ""

        can = str2 if len(str2) <= len(str1) else str1

        for i in range(len(can), 0, -1):
            gcd = can[:i]
            if len(str1) % len(gcd) == 0 and len(str2) % len(gcd) == 0:
                if gcd * (len(str1) // len(gcd)) == str1 and gcd * (len(str2) // len(gcd)) == str2:
                    return gcd

        return ""

# Test
s = Solution()
result = s.gcdOfStrings(
    "CPFYNICPFYNICPFYNICPFYNICPFYNI", 
    "CPFYNICPFYNICPFYNICPFYNICPFYNICPFYNICPFYNICPFYNICPFYNICPFYNICPFYNICPFYNICPFYNICPFYNICPFYNICPFYNICPFYNI"
)
print(result)  # Should output: CPFYNI


CPFYNI


In [51]:
class Solution(object):
    def gcdOfStrings(self, str1, str2):
        # Input validation
        if len(str1) < 1 or len(str1) > 1000 or not str1.isalpha() or not str1.isupper():
            return ""
        if len(str2) < 1 or len(str2) > 1000 or not str2.isalpha() or not str2.isupper():
            return ""

        # Check if str1 + str2 == str2 + str1
        if str1 + str2 != str2 + str1:
            return ""

        # Shorter string as candidate
        candidate = str2 if len(str2) < len(str1) else str1

        # Now check smallest prefix of candidate that can construct both strings
        for i in range(1, len(candidate) + 1):
            prefix = candidate[:i]
            if len(str1) % len(prefix) == 0 and len(str2) % len(prefix) == 0:
                if prefix * (len(str1) // len(prefix)) == str1 and prefix * (len(str2) // len(prefix)) == str2:
                    return prefix

        return ""


In [52]:
class Solution(object):
    def gcdOfStrings(self, str1, str2):
        # Input validation based on your constraints
        if len(str1) < 1 or len(str1) > 100 or not str1.isalpha() or not str1.isupper():
            return ""
        if len(str2) < 1 or len(str2) > 100 or not str2.isalpha() or not str2.isupper():
            return ""

        # Check if strings can have a common divisor
        if str1 + str2 != str2 + str1:
            return ""

        # Use the shorter string as the initial GCD
        gcd = str2 if len(str2) <= len(str1) else str1

        # Now shrink gcd if needed, from end, until it fits both strings
        while gcd:
            if str1 == gcd * (len(str1) // len(gcd)) and str2 == gcd * (len(str2) // len(gcd)):
                return gcd
            gcd = gcd[:-1]  # reduce by one character

        return ""


In [ ]:
class Solution(object):
    def gcdOfStrings(self,)

In [60]:
import numpy as np

matrix=np.zeros((3,3),dtype=int)

print (matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [71]:
matrix=[]

rows=4
cols=4

for i in range(rows):
    row=[]
    for j in range(cols):
        row.append(0)
    matrix.append(row)

print (matrix)

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]


In [76]:
rows=2
cols=2

mat=[[[]for i in range(cols)]for j in range(rows)]
print (mat)

[[[], []], [[], []]]


In [86]:
rows = 2
cols = 5
num = 0

mat = [[num + i + j for i in range(cols)] for j in range(rows)]
print(mat)


[[0, 1, 2, 3, 4], [1, 2, 3, 4, 5]]


In [91]:
dic1={
    'name':'Moeez',
    'class':'bscs',
    'section':'H'
}

dic1['year']='2022'

print(dic1)


{'name': 'Moeez', 'class': 'bscs', 'section': 'H', 'year': '2022'}


In [94]:
rollno={}
start=6600
total_students=100
rollno={x:start+1 for i in range(total_students)}
print(rollno)

NameError: name 'x' is not defined

In [96]:
rollno=[]
start=6000

total_students=100

rollno=[start+i for i in range(total_students)]

print(rollno)

[6000, 6001, 6002, 6003, 6004, 6005, 6006, 6007, 6008, 6009, 6010, 6011, 6012, 6013, 6014, 6015, 6016, 6017, 6018, 6019, 6020, 6021, 6022, 6023, 6024, 6025, 6026, 6027, 6028, 6029, 6030, 6031, 6032, 6033, 6034, 6035, 6036, 6037, 6038, 6039, 6040, 6041, 6042, 6043, 6044, 6045, 6046, 6047, 6048, 6049, 6050, 6051, 6052, 6053, 6054, 6055, 6056, 6057, 6058, 6059, 6060, 6061, 6062, 6063, 6064, 6065, 6066, 6067, 6068, 6069, 6070, 6071, 6072, 6073, 6074, 6075, 6076, 6077, 6078, 6079, 6080, 6081, 6082, 6083, 6084, 6085, 6086, 6087, 6088, 6089, 6090, 6091, 6092, 6093, 6094, 6095, 6096, 6097, 6098, 6099]


In [100]:
student_info={
    'name':'Moeez',
    'rollno':'6645',
    'section':'6h',
    'subjects':['cc','pdc','ai','se']
}

student_info.get('subjects')
list(student_info.items())


[('name', 'Moeez'),
 ('rollno', '6645'),
 ('section', '6h'),
 ('subjects', ['cc', 'pdc', 'ai', 'se'])]

In [108]:
check=[1,23,4,3,2,3,2]
print(check)

[1, 23, 4, 3, 2, 3, 2]


In [120]:
students = [
    {
        "name": "Areeba Khan",
        "roll": "CS2023-001",
        "year": "BSCS 3rd Year",
        "subjects": ["Data Structures", "AI", "Databases"]
    },
    {
        "name": "Hassan Ali",
        "roll": "CS2023-002",
        "year": "BSCS 3rd Year",
        "subjects": ["Computer Networks", "Machine Learning", "Web Development"]
    },
    {
        "name": "Fatima Noor",
        "roll": "CS2023-003",
        "year": "BSCS 3rd Year",
        "subjects": ["Compiler Construction", "AI", "Software Engineering"]
    },
    {
        "name": "Zain Ahmed",
        "roll": "CS2023-004",
        "year": "BSCS 3rd Year",
        "subjects": ["OOP", "Mobile App Dev", "Operating Systems"]
    },
    {
        "name": "Summaiyyah Tariq",
        "roll": "CS2023-005",
        "year": "BSCS 3rd Year",
        "subjects": ["Data Science", "NLP", "Human Computer Interaction"]
    },
    {
        "name": "Usman Rauf",
        "roll": "CS2023-006",
        "year": "BSCS 3rd Year",
        "subjects": ["Cybersecurity", "Blockchain", "AI"]
    },
    {
        "name": "Tehreem Fatima",
        "roll": "CS2023-007",
        "year": "BSCS 3rd Year",
        "subjects": ["Deep Learning", "Software Project Management", "Cloud Computing"]
    },
    {
        "name": "Moiz Rehman",
        "roll": "CS2023-008",
        "year": "BSCS 3rd Year",
        "subjects": ["Algorithms", "IoT", "Digital Logic Design"]
    },
    {
        "name": "Urwa Saeed",
        "roll": "CS2023-009",
        "year": "BSCS 3rd Year",
        "subjects": ["Database Systems", "Information Retrieval", "Machine Learning"]
    },
    {
        "name": "Ahsan Iqbal",
        "roll": "CS2023-010",
        "year": "BSCS 3rd Year",
        "subjects": ["Image Processing", "Python Programming", "Data Structures"]
    }
]

for student in students:
    print("The student: ",student.get("name"), "has roll no." ,student.get("roll"))





The student:  Areeba Khan has roll no. CS2023-001
The student:  Hassan Ali has roll no. CS2023-002
The student:  Fatima Noor has roll no. CS2023-003
The student:  Zain Ahmed has roll no. CS2023-004
The student:  Summaiyyah Tariq has roll no. CS2023-005
The student:  Usman Rauf has roll no. CS2023-006
The student:  Tehreem Fatima has roll no. CS2023-007
The student:  Moiz Rehman has roll no. CS2023-008
The student:  Urwa Saeed has roll no. CS2023-009
The student:  Ahsan Iqbal has roll no. CS2023-010


In [122]:
students = [
    (
        ("name", "Areeba Khan"),
        ("roll", "CS2023-001"),
        ("year", "BSCS 3rd Year"),
        ("subjects", ["Data Structures", "AI", "Databases"])
    ),
    (
        ("name", "Hassan Ali"),
        ("roll", "CS2023-002"),
        ("year", "BSCS 3rd Year"),
        ("subjects", ["Computer Networks", "Machine Learning", "Web Development"])
    ),
    (
        ("name", "Fatima Noor"),
        ("roll", "CS2023-003"),
        ("year", "BSCS 3rd Year"),
        ("subjects", ["Compiler Construction", "AI", "Software Engineering"])
    ),
    (
        ("name", "Zain Ahmed"),
        ("roll", "CS2023-004"),
        ("year", "BSCS 3rd Year"),
        ("subjects", ["OOP", "Mobile App Dev", "Operating Systems"])
    ),
    (
        ("name", "Summaiyyah Tariq"),
        ("roll", "CS2023-005"),
        ("year", "BSCS 3rd Year"),
        ("subjects", ["Data Science", "NLP", "Human Computer Interaction"])
    ),
    (
        ("name", "Usman Rauf"),
        ("roll", "CS2023-006"),
        ("year", "BSCS 3rd Year"),
        ("subjects", ["Cybersecurity", "Blockchain", "AI"])
    ),
    (
        ("name", "Tehreem Fatima"),
        ("roll", "CS2023-007"),
        ("year", "BSCS 3rd Year"),
        ("subjects", ["Deep Learning", "Software Project Management", "Cloud Computing"])
    ),
    (
        ("name", "Moiz Rehman"),
        ("roll", "CS2023-008"),
        ("year", "BSCS 3rd Year"),
        ("subjects", ["Algorithms", "IoT", "Digital Logic Design"])
    ),
    (
        ("name", "Urwa Saeed"),
        ("roll", "CS2023-009"),
        ("year", "BSCS 3rd Year"),
        ("subjects", ["Database Systems", "Information Retrieval", "Machine Learning"])
    ),
    (
        ("name", "Ahsan Iqbal"),
        ("roll", "CS2023-010"),
        ("year", "BSCS 3rd Year"),
        ("subjects", ["Image Processing", "Python Programming", "Data Structures"])
    )
]




(('name', 'Hassan Ali'), ('roll', 'CS2023-002'), ('year', 'BSCS 3rd Year'), ('subjects', ['Computer Networks', 'Machine Learning', 'Web Development']))


In [131]:
list= [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
listr=[i for i in list if i%3==0]
print(listr)


[0, 9, 36, 81]


In [141]:
#a-front + b-front + a-back + b-back  // Expected output abcmndegop

def splitandmerge(a,b):
    if len(a)%2==0:
        a_front=a[:len(a)//2]
        a_back=a[(len(a)//2):]
    else:
        a_front=a[:(len(a)//2)+1]
        a_back=a[(len(a)//2)+1:]
    
    if len(b)%2==0:
        b_front=b[:len(b)//2]
        b_back=b[(len(b)//2):]
    else:
        b_front=b[:(len(b)//2)+1]
        b_back=b[(len(b)//2)+1:]
    
    merger=a_front+b_front+a_back+b_back
    return merger


splitandmerge("abcdeg","mnop")

'abcmndegop'

In [171]:
tuples=[(1, 7), (1, 3), (3, 4, 5), (2, 2)]

num=[]
size=len(tuples)
for tup in tuples:
    num.append(tup[-1])

j=0  
while j<size-1:
    for i in range(len(tuples)-1):
        if num[i]>num[i+1]:
            temp=tuples[i]
            tuples[i]=tuples[i+1]
            tuples[i+1]=temp
    
    for i in range(len(tuples)):
        num[i]=tuples[i][-1]
    
    j=j+1

print(tuples)



[(2, 2), (1, 3), (3, 4, 5), (1, 7)]


In [188]:
tuple=(1,5,7,8,4)
ntuple=()
for i in range(len(tuple)-1):
    ntuple+=(tuple[i]*tuple[i+1],)

print(ntuple)


(5, 35, 56, 32)


In [175]:
list=[1,2,4,5,3]
nlist=[list[n]*list[n+1] for n in range(len(list)-1)]
print(nlist)


[2, 8, 20, 15]


In [205]:
def searchbinary(arr,s):
    s=int(s)
    arr=[int(n) for n in arr]

    m=len(arr)//2
    if arr[m]==s:
        return m
    
    if s>arr[m]:
        result=searchbinary(arr[m+1:],s)
        if result==-1:
            return -1
        else:
            return m+1+result
    else:
        return searchbinary(arr[:m],s)

    return -1


arr=['1','2','3','4','5','6','7','8']
s=4
searchbinary(arr,s)

3

In [ ]:
def searchbinary(arr, s):
    s = int(s)  # convert s to int early
    arr = [int(x) for x in arr]  # convert all elements in arr to int

    m = len(arr) // 2
    if arr[m] == s:
        return m

    if s > arr[m]:
        result = searchbinary(arr[m+1:], s)
        if result == -1:
            return -1
        else:
            return m + 1 + result  # adjust index
    else:
        return searchbinary(arr[:m], s)

    return -1

arr=['1','2','3','4','5','6','7','8']
s=4
searchbinary(arr,s)


2

In [218]:
list=[1, 2, 2, 3, 4, 2]
dic={
}
for i in list:
    if i in dic:
        dic[i]+=1
    else:
        dic[i]=1

print(dic)

{1: 1, 2: 3, 3: 1, 4: 1}


In [221]:
list_of_dicts = [
    {'name': 'Alice', 'age': 25},
    {'name': 'Bob', 'age': 30},
    {'name': 'Charlie', 'age': 25},
    {'name': 'David', 'age': 40}
]

key="age"
value=25

newdict={}
j=0
for i in list_of_dicts:
    if i.get(key)==value:
        newdict[j]=i
        j=j+1
        
print(newdict)


{0: {'name': 'Alice', 'age': 25}, 1: {'name': 'Charlie', 'age': 25}}


In [10]:
import numpy as np

class Solution(object):
    def kidsWithCandies(self, candies, extraCandies):
        candies=[int(x) for x in candies]
        max=0
        for i in candies:
            if i>max:
                max=i

        list=[(candies[i]+extraCandies)>=max for i in range(len(candies))]
        return list

s=Solution()
can=[1,2,3,4,5,6]
ec=3
s.kidsWithCandies(can,ec)

[False, False, True, True, True, True]

In [74]:
class Solution(object):
    def canPlaceFlowers(self, flowerbed, n):
        flowerbed = [int(x) for x in flowerbed]
        tp = 0
        i = 0
        c = False

        # Special case: only 1 element
        if len(flowerbed) == 1:
            if flowerbed[0] == 0:
                tp = 1

        elif len(flowerbed) == 2:
            if flowerbed[0] == 0 and flowerbed[1] == 0:
                tp = 1

        else:
            while i < len(flowerbed):
                # For first position
                if i == 0:
                    if flowerbed[i] == 0 and flowerbed[i + 1] == 0:
                        tp += 1
                        flowerbed[i] = 1
                        i += 1  # skip next
                # For last position
                elif i == len(flowerbed) - 1:
                    if flowerbed[i] == 0 and flowerbed[i - 1] == 0:
                        tp += 1
                        flowerbed[i] = 1
                # For middle positions
                elif flowerbed[i] == 0 and flowerbed[i - 1] == 0 and flowerbed[i + 1] == 0:
                    tp += 1
                    flowerbed[i] = 1
                    i += 1  # skip next
                i += 1  # move to next index

        if n > tp:
            return False
        else:
            return True



s = Solution()
arr = [1, 0, 0, 0, 1]
n = 1
print(s.canPlaceFlowers(arr, n))  


True


In [21]:
class Node(object):
    def __init__(self,value):
        self.value=value
        self.children=[]



root=Node("A")
child1=Node("B")
child2=Node("C")

c1c1=Node("D")
c1c2=Node("E")
c2c1=Node("F")
c2c2=Node("G")

root.children.append(child1)
root.children.append(child2)

child1.children.append(c1c1)
child1.children.append(c1c2)

child2.children.append(c2c1)
child2.children.append(c2c2)


def printdfs(root):
        list=[root.value]
        for i in root.children:
            list.extend(printdfs(i))

        return list


print(printdfs(root))


['A', 'B', 'D', 'E', 'C', 'F', 'G']


In [31]:
from collections import deque

class Node(object):
    def __init__(self,value):
        self.value=value
        self.children=[]



root=Node("A")
child1=Node("B")
child2=Node("C")

c1c1=Node("D")
c1c2=Node("E")
c2c1=Node("F")
c2c2=Node("G")

root.children.append(child1)
root.children.append(child2)

child1.children.append(c1c1)
child1.children.append(c1c2)

child2.children.append(c2c1)
child2.children.append(c2c2)


def printbfs(root):
    list=deque([root])
    result=[]
    while list:
        val=list.popleft()
        result.append(val.value)

        for i in val.children:
            list.append(i)
    
    return result


print(printbfs(root))


['A', 'B', 'C', 'D', 'E', 'F', 'G']


In [2]:
rows=3
cols=3

matrix=[]

for i in range(rows):
    row=[]
    for j in range(cols):
        col=row.append(0)
    matrix.append(col)

print(matrix)





[None, None, None]


In [ ]:
import numpy as np

arr=np.array([1,2,3,4])
print(arr)


mean=np.mean(arr)
print(mean)

ran=[]
for i in range(10):
    ran.append(np.random.randn())

#print(ran)

rarr=np.random.randn(10)
print(rarr)


matrix=np.zeros([3,3])
print(matrix)

rm=np.random.randn(3,4)
print(rm)

rm1=np.random.rand(5)
print(rm1)

rm2=np.random.randint(1,10,size=(4,4))
print(rm2)













[1 2 3 4]
2.5
[ 1.67045475 -0.37908566 -0.7857627   0.38926514  0.98767276 -0.30655869
 -0.47695173  1.24826258 -1.10461309 -0.43818246]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[-0.97186451 -1.28645861 -0.68884766  0.65822597]
 [-0.61210279  0.14924833  1.32306971 -0.20644744]
 [-1.3314849   0.05976354 -1.93455845 -0.50903774]]
[0.85549612 0.84227552 0.50141774 0.11418229 0.5644058 ]
[[2 4 2 6]
 [7 5 5 9]
 [2 4 8 6]
 [2 3 6 3]]


In [65]:
print(np.zeros([2,3])+1)

[[1. 1. 1.]
 [1. 1. 1.]]


In [75]:
matrix=np.random.randint(1,5,size=(4,4))
print("Our matrix is:" )
print(matrix)

matrix=matrix + 2*np.ones((4,4))
print (matrix)



Our matrix is:
[[4 1 2 3]
 [1 4 1 1]
 [4 2 1 1]
 [2 4 1 3]]
[[6. 3. 4. 5.]
 [3. 6. 3. 3.]
 [6. 4. 3. 3.]
 [4. 6. 3. 5.]]


In [117]:
import numpy as np

dfs_path=[]
bfs_path=[]

def readfile(filename):
    matrix = []
    with open(filename, "r") as file:
        for line in file:
            row = []
            for element in line.strip().split():  # split by space
                val = element.strip()
                if val.isdigit():
                    row.append(int(val))
                else:
                    try:
                        row.append(float(val))  # just in case there are floats
                    except:
                        row.append(val)  # keep strings like 'S' or 'G'
            matrix.append(row)
    return matrix

def visitdfs(m, r, c, visited):
    rows = len(m)
    cols = len(m[0])

    if r < 0 or r >= rows or c < 0 or c >= cols:
        return

    if visited[r][c] or m[r][c] == 1:
        return

    visited[r][c] = True
    dfs_path.append((r, c))

    # Move in all 4 directions
    visitdfs(m, r + 1, c, visited)  # down
    visitdfs(m, r, c + 1, visited)  # right
    visitdfs(m, r - 1, c, visited)  # up
    visitdfs(m, r, c - 1, visited)  # left

    

# Example usage:
n = "maze.txt"
m = readfile(n)
visited=[[False for i in range(len(m[0]))]for j in range(len(m))]
visitdfs(m,0,0,visited)
print(dfs_path)

[(0, 0), (0, 1), (0, 2), (1, 2), (2, 2), (3, 2), (4, 2), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (4, 6), (3, 6), (3, 5), (3, 4), (2, 4), (1, 4), (1, 5), (1, 6), (0, 6), (0, 5), (1, 3), (0, 3), (3, 3), (5, 1), (4, 1), (4, 0), (5, 0), (3, 0), (2, 0)]


In [88]:
r=0
c=0

matrix[r][c]="n"

print(matrix[r][c])

ValueError: could not convert string to float: 'n'

In [12]:
dfs_path=[]
path=[]

def makematrix(filename):
    matrix=[]
    with open(filename, "r") as file:
        for line in file:
            row=[]
            for element in line.strip().split():
                row.append(element)
            
            matrix.append(row)
    
    return matrix


def findgoaldfs(m,r,c,visited):
    rows=len(m)
    cols=len(m[0])

    if r<0 or c>=cols or r>=rows or c<0:
        return
    
    if m[r][c]=="1" or visited[r][c]==True:
        return
    
    if m[r][c]=="G":
        dfs_path.append(path)
        path=[]
    
    visited[r][c]=True
    path.append((r,c))

    findgoaldfs(m,r-1,c,visited)
    findgoaldfs(m,r,c-1,visited)
    findgoaldfs(m,r+1,c,visited)
    findgoaldfs(m,r,c+1,visited)





filename="maze.txt"
m=makematrix(filename)
r=0
c=0
visited=[[False for i in range(len(m[0]))]for j in range(len(m))]
findgoaldfs(m,r,c,visited)
print(dfs_path)


UnboundLocalError: cannot access local variable 'path' where it is not associated with a value

In [10]:
def makematrix(filename):
    matrix=[]
    with open(filename, "r") as file:
        for line in file:
            row=[]
            for element in line.strip().split():
                row.append(element)
            matrix.append(row)
    return matrix

    

n="maze.txt"
m=makematrix(n)
print("2")

2
